# Generated by Django 5.0.3 on 2024-04-16 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_nascita_alter_user_email_alter_user_quota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scambio',
            name='bdt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.bdt'),
        ),
    ]
