# Generated by Django 5.0.3 on 2024-04-20 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_scambio_donatore_remove_scambio_ricevente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='evento',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
