# Generated by Django 5.0.3 on 2024-04-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_evento_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saldo',
            field=models.IntegerField(null=True),
        ),
    ]
