# Generated by Django 5.0.3 on 2024-04-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_user_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scambio',
            name='data',
            field=models.DateField(),
        ),
    ]
