# Generated by Django 5.0.4 on 2024-04-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_scambio_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ore_date',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ore_ricevute',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='saldo',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
