# Generated by Django 5.0.4 on 2024-04-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_ore_date_user_ore_ricevute_alter_user_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='foto',
            field=models.ImageField(default='no-image.png', null=True, upload_to=''),
        ),
    ]
