# Generated by Django 5.0.4 on 2024-04-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_evento_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='foto',
            field=models.ImageField(default='no-image.png', null=True, upload_to=''),
        ),
    ]
