# Generated by Django 5.0.4 on 2024-04-22 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_area_categoria_area_scambio_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='bdt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.bdt'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='bdt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.bdt'),
        ),
    ]
