# Generated by Django 5.0.4 on 2024-04-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_area_bdt_categoria_bdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdt',
            name='logo',
            field=models.ImageField(default='no-image.png', null=True, upload_to=''),
        ),
    ]
