# Generated by Django 5.0.4 on 2024-04-24 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_bdt_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scambio',
            name='donatore',
        ),
        migrations.RemoveField(
            model_name='scambio',
            name='ricevente',
        ),
        migrations.AddField(
            model_name='scambio',
            name='donatore',
            field=models.ManyToManyField(null=True, related_name='donatore', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scambio',
            name='ricevente',
            field=models.ManyToManyField(null=True, related_name='ricevente', to=settings.AUTH_USER_MODEL),
        ),
    ]
