# Generated by Django 5.0.4 on 2024-04-24 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_scambio_donatore_remove_scambio_ricevente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scambio',
            name='donatore',
            field=models.ManyToManyField(related_name='donatori', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scambio',
            name='ricevente',
            field=models.ManyToManyField(related_name='riceventi', to=settings.AUTH_USER_MODEL),
        ),
    ]
