# Generated by Django 5.0.4 on 2024-04-24 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_scambio_donatore_alter_scambio_ricevente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scambio',
            name='donatore',
        ),
        migrations.RemoveField(
            model_name='scambio',
            name='ricevente',
        ),
        migrations.AddField(
            model_name='scambio',
            name='donatore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donatore', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scambio',
            name='ricevente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ricevente', to=settings.AUTH_USER_MODEL),
        ),
    ]
