# Generated by Django 5.0.4 on 2024-04-24 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_scambio_donatore_remove_scambio_ricevente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scambio',
            name='donatore',
        ),
        migrations.RemoveField(
            model_name='scambio',
            name='ricevente',
        ),
        migrations.AddField(
            model_name='scambio',
            name='donatori',
            field=models.ManyToManyField(related_name='donatori', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scambio',
            name='riceventi',
            field=models.ManyToManyField(related_name='riceventi', to=settings.AUTH_USER_MODEL),
        ),
    ]
