# Generated by Django 5.0.4 on 2024-04-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_scambio_donatore_remove_scambio_ricevente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ore_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ore_ricevute',
        ),
        migrations.RemoveField(
            model_name='user',
            name='saldo',
        ),
        migrations.AlterField(
            model_name='scambio',
            name='note',
            field=models.TextField(),
        ),
    ]
