# Generated by Django 5.0.4 on 2024-04-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_user_ore_date_remove_user_ore_ricevute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='propensione',
            field=models.ManyToManyField(related_name='propensione', to='base.categoria'),
        ),
    ]
