# Generated by Django 5.0.4 on 2024-04-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_user_propensione'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome']},
        ),
        migrations.RenameField(
            model_name='bdt',
            old_name='logo',
            new_name='logo_bdt',
        ),
        migrations.RenameField(
            model_name='bdt',
            old_name='nome',
            new_name='nome_bdt',
        ),
    ]
