# Generated by Django 5.0.4 on 2024-04-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_area_options_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saldo',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
