# Generated by Django 5.0.4 on 2024-04-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_user_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='scambio',
            name='tesoretto',
            field=models.IntegerField(null=True),
        ),
    ]
