# Generated by Django 5.0.4 on 2024-04-28 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_scambio_tesoretto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scambio',
            name='tesoretto',
        ),
    ]
