# Generated by Django 5.0.4 on 2024-05-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_scambio_tesoretto'),
    ]

    operations = [
        migrations.AddField(
            model_name='scambio',
            name='nomi_donatori',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='scambio',
            name='nomi_riceventi',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
