# Generated by Django 5.0.4 on 2024-05-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_scambio_nomi_donatori_scambio_nomi_riceventi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='propensione',
            field=models.ManyToManyField(related_name='propensione', to='base.area'),
        ),
    ]
