# Generated by Django 5.0.4 on 2024-05-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_user_propensione'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['cognome']},
        ),
        migrations.AlterField(
            model_name='evento',
            name='descrizione',
            field=models.TextField(),
        ),
    ]
