# Generated by Django 5.0.4 on 2024-06-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_user_options_alter_evento_descrizione'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anni_pag',
            field=models.TextField(null=True),
        ),
    ]
