# Generated by Django 5.0.4 on 2024-06-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_user_anni_pag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ore_iniz',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
